query GetAllStorageLocations {
  allStorageLocations {
    id
    locationCode
    maxCapacity
    unitType
    storageType
    sectionName
    createdAt
    warehouse {
      id
      warehouseName
      warehouseCode
    }
    user {
      id
      firstName
      lastName
      email
    }
  }
}
